from __future__ import annotations

import json
import re
import time
from copy import deepcopy
from pathlib import Path
from pprint import pformat
from typing import Any

import requests
from black import FileMode, format_str
from jinja2 import Environment, FileSystemLoader


BASE_DIR = Path(__file__).resolve().parent
TEMPLATE_ENV = Environment(
    loader=FileSystemLoader(BASE_DIR / "templates"),
    trim_blocks=True,
    lstrip_blocks=True,
)


BROWSER_TASK_TYPES = {
    "navigate",
    "click",
    "input",
    "select",
    "wait",
    "execute_script",
    "extract",
}


def slugify(name: str) -> str:
    normalized = re.sub(r"[^\w\u4e00-\u9fff-]+", "_", name.strip())
    normalized = normalized.strip("_")
    return normalized or "generated_script"


def validate_config(config: dict[str, Any]) -> list[str]:
    issues: list[str] = []

    if not config.get("tasks"):
        issues.append("tasks 不能为空")

    output_dir = config.get("global", {}).get("outputDirectory", "").strip()
    if not output_dir:
        issues.append("global.outputDirectory 未设置")

    login = config.get("login", {})
    if login.get("method") == "password":
        for field in (
            "url",
            "usernameSelector",
            "passwordSelector",
            "submitSelector",
            "username",
            "password",
        ):
            if not str(login.get(field, "")).strip():
                issues.append(f"password 登录缺少字段: {field}")

    if login.get("method") == "wallet":
        for field in ("rpcUrl", "privateKeyEnvVar"):
            if not str(login.get(field, "")).strip():
                issues.append(f"wallet 登录缺少字段: {field}")

    if config.get("proxy", {}).get("enabled"):
        proxy = config["proxy"]
        if proxy.get("mode") == "single" and not str(proxy.get("single", "")).strip():
            issues.append("代理模式为 single 时必须填写 proxy.single")
        if proxy.get("mode") == "list" and not proxy.get("list"):
            issues.append("代理模式为 list 时必须至少提供一条代理")

    return issues


def requires_browser(login: dict[str, Any], tasks: list[dict[str, Any]]) -> bool:
    if login.get("method") in {"password"}:
        return True

    if login.get("method") == "cookie" and login.get("injectionMode") == "cookie":
        return True

    for task in tasks:
        task_type = task.get("type")
        if task_type in BROWSER_TASK_TYPES:
            return True
        if task_type == "condition":
            if requires_browser(login, task.get("thenTasks", [])) or requires_browser(
                login, task.get("elseTasks", [])
            ):
                return True
        if task_type == "loop":
            if requires_browser(login, task.get("tasks", [])):
                return True

    return False


def collect_dependencies(config: dict[str, Any], include_browser: bool) -> list[str]:
    dependencies = ["requests>=2.32.0"]
    if include_browser:
        dependencies.append("playwright>=1.55.0")
    if config.get("login", {}).get("method") == "wallet":
        dependencies.append("web3>=7.0.0")
    if config.get("proxy", {}).get("enabled") and config.get("proxy", {}).get("type") == "socks5":
        dependencies.append("PySocks>=1.7.1")
    return dependencies


def build_env_example(config: dict[str, Any]) -> str:
    lines = ["# Generated by Script Generator", "# Fill values before running the script"]
    login = config.get("login", {})
    if login.get("method") == "wallet":
        lines.append(f"{login.get('privateKeyEnvVar', 'PRIVATE_KEY')}=")
    return "\n".join(lines) + "\n"


def prepare_runtime_config(config: dict[str, Any]) -> dict[str, Any]:
    runtime_config = deepcopy(config)
    runtime_config.setdefault("meta", {})
    runtime_config.setdefault("global", {})
    runtime_config.setdefault("login", {})
    runtime_config.setdefault("proxy", {})
    runtime_config.setdefault("tasks", [])
    return runtime_config


def render_script(config: dict[str, Any]) -> tuple[str, list[str]]:
    runtime_config = prepare_runtime_config(config)
    include_browser = requires_browser(runtime_config.get("login", {}), runtime_config.get("tasks", []))
    dependencies = collect_dependencies(runtime_config, include_browser)
    template = TEMPLATE_ENV.get_template("script.py.j2")
    rendered = template.render(
        config_json=pformat(runtime_config, width=100, sort_dicts=False),
        include_browser=include_browser,
        include_web3=runtime_config.get("login", {}).get("method") == "wallet",
        dependency_list=dependencies,
    )

    try:
        rendered = format_str(rendered, mode=FileMode())
    except Exception:
        pass

    return rendered, dependencies


def write_generation_artifacts(config: dict[str, Any], output_directory: str) -> dict[str, Any]:
    issues = validate_config(config)
    if issues:
        raise ValueError("; ".join(issues))

    output_dir = Path(output_directory)
    output_dir.mkdir(parents=True, exist_ok=True)

    script_name = slugify(config.get("meta", {}).get("name", "generated_script"))
    script_content, dependencies = render_script(config)
    requirements_content = "\n".join(dependencies) + "\n"
    env_example_content = build_env_example(config)

    script_path = output_dir / f"{script_name}.py"
    requirements_path = output_dir / "requirements.txt"
    env_example_path = output_dir / ".env.example"

    script_path.write_text(script_content, encoding="utf-8")
    requirements_path.write_text(requirements_content, encoding="utf-8")
    env_example_path.write_text(env_example_content, encoding="utf-8")

    return {
        "success": True,
        "scriptPath": str(script_path),
        "requirementsPath": str(requirements_path),
        "envExamplePath": str(env_example_path),
        "outputDirectory": str(output_dir),
        "scriptContent": script_content,
        "requirementsContent": requirements_content,
        "dependencyList": dependencies,
    }


def validate_proxy(proxy_url: str, timeout_seconds: int) -> dict[str, Any]:
    started = time.perf_counter()
    proxies = {"http": proxy_url, "https": proxy_url}
    try:
        response = requests.get(
            "https://httpbin.org/ip",
            timeout=timeout_seconds,
            proxies=proxies,
        )
        elapsed_ms = int((time.perf_counter() - started) * 1000)
        return {
            "success": True,
            "ok": response.ok,
            "message": f"HTTP {response.status_code} {response.text[:120]}",
            "elapsedMs": elapsed_ms,
        }
    except Exception as exc:  # pragma: no cover - network failure path
        elapsed_ms = int((time.perf_counter() - started) * 1000)
        return {
            "success": True,
            "ok": False,
            "message": str(exc),
            "elapsedMs": elapsed_ms,
        }
